name: ci
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        package: [evil, magit, realgud, org-contacts, which-key-posframe]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: melpa/melpa
        fetch-depth: 1
        persist-credentials: false
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: package-build
        fetch-depth: 1
        persist-credentials: false
    - name: Build ${{ matrix.package }}
      uses: ./package-build
      env:
        NOERROR: nil
        BUILD_PACKAGES: ${{ matrix.package }}
      with:
        args: build-channels
