#!/bin/bash

set -euo pipefail

THIS_DIR=$(dirname "$0")
logdir="$1"
shift
parquetdir="$1"

if [ -z "$logdir" ] || [ -z "$parquetdir" ]; then
    echo "usage: $0 logdir parquetdir" >&2
    exit 1
fi

logcat() {
    local logfile="$1"
    if [ "${logfile##*.}" = "gz" ]; then
        gunzip -c "$logfile"
    else
        cat "$logfile"
    fi
}
function refresh_parquet() {
    echo "Checking for stale or missing parquet files..." >&2
    find "$logdir" -type f -name '*access.log*' -print0 | while IFS= read -r -d $'\0' f; do
        parquet_file="$parquetdir/$(realpath --relative-to "$logdir" "$f").parquet"
        if ! [ "$parquet_file" -nt "$f" ]; then
            echo "Building $parquet_file" >&2
            p=$(mktemp)
            logcat "$f" | "$THIS_DIR"/log_to_parquet.py > "$p"
            mkdir -p "$(dirname "$parquet_file")"
            mv "$p" "$parquet_file"
        fi
    done
}

# TODO: remove parquet files that no longer have corresponding log files

mkdir -p "$parquetdir"
refresh_parquet
"$THIS_DIR/summarise" "$parquetdir"
