((emacs-lisp-mode . ((flycheck-disabled-checkers '(emacs-lisp emacs-lisp-checkdoc))))
 (nil . ((eval . (when (and (buffer-file-name)
                            (file-regular-p (buffer-file-name))
                            (string-match-p "^[^.]" (buffer-file-name)))
                   (emacs-lisp-mode)
                   (when (fboundp 'flycheck-mode)
                     (flycheck-mode -1))
                   (unless (featurep 'package-build)
                     (let ((load-path (cons ".." load-path)))
                       (require 'package-build)))
                   (package-build-minor-mode))))))
