language: ruby
dist: xenial

addons:
  apt:
    packages:
    - git
    - mercurial
    - texinfo

before_install:
  - sudo apt-get -yq update
  - sudo apt-get -yq install git mercurial texinfo

  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH

  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  # Use cask to install development dependencies
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

  # Work around SSL-related failures in Travis, see
  # https://stackoverflow.com/questions/21477683/mercurial-https-clone-abort-error-wrong-version-number
  - echo "[ui]\ntls = False" > $HOME/.hgrc

env:
  #- EVM_EMACS=emacs-23.4-travis
  #- EVM_EMACS=emacs-24.1-travis
  #- EVM_EMACS=emacs-24.2-travis
  #- EVM_EMACS=emacs-24.3-travis
  #- EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  #- EVM_EMACS=emacs-git-snapshot-travis

script:
  ./run-travis-ci.sh
