language: emacs-lisp
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
env:
  #- EMACS=emacs
  - EMACS=emacs24
  #- EMACS=emacs-snapshot
script:
  ./run-travis-ci.sh