#!/bin/bash

# (load-file "~/.emacs.d/elisp/package-build.el")
# (package-build-archive

for pkg in $@; do
	echo "Building package: $pkg"
	emacs --batch -l package-build.el --eval "(package-build-archive \"$pkg\")"
	echo
	echo
done


