#!/bin/bash

BASEDIR=`dirname $0`

cd ${BASEDIR} || exit 1


function melpa_clear_packages {
    date
    rm -rf packages/*
    echo
}


function melpa_build_pkglist {
    echo "*** `date` -- Building all packages..."
    emacs --batch -l package-build.el --eval "(package-build-all)"
    echo
}

function melpa_generate_html {
    echo "*** `date` -- Building html..."
    cd html || return 1
    erb index.erb > index.md
    pandoc --template=template.html --css=style.css -s --mathml -t html --smart index.md > index.html
    cd ..
    echo
}

function trim {
    echo $1
}

function print_usage {
    echo "usage: $0 [-h | -?] [clear | build | html ]"
}

args=`getopt h $*`
errcode=$?

if [[ "$errcode" > 0 ]]; then
    print_usage
    exit $errcode
fi

set -- $args

for i; do
    case "$i" in
        -h | -\?) print_usage
            shift
            exit
            ;;
        --) shift
            break
            ;;
    esac
done


if [[ "$#" == "0" ]]; then
    set -- build index
fi

for i; do
    case $i in
        clear ) melpa_clear_packages ;;
        build ) melpa_build_pkglist ;;
        html | index ) melpa_generate_html ;;
    esac
    shift
done

exit 1




