#!/bin/sh 
:;exec emacs --script "$0" "$@"

(defun read-from-file (file-name)
  "read one lisp expression from a file"
  (cond
   ((file-exists-p file-name)
    (with-temp-buffer
      (insert-file-contents-literally file-name)
      (goto-char (point-min))
      (car
       (read-from-string
        (buffer-substring-no-properties (point-min) (point-max))))))))

(message (prin1-to-string command-line-args-left))
(defun process-one (file-name)
  (let ((config
         (read-from-file
          (expand-file-name ".config" (expand-file-name file-name "epkgs")))))
    (princ
     (pp-to-string
      (cons
       (intern file-name)
       (plist-put
        (plist-put
         nil
         :url
         (plist-get config :url))
        :fetcher
        (plist-get config :fetcher)))
      ))))

(mapc 'process-one command-line-args-left)
