#!/bin/bash -e

export LANG=en_US.UTF-8

function kill_all_jobs { jobs -p | xargs kill; }
trap kill_all_jobs SIGINT SIGTERM

function build_all {
    PATH=$HOME/.cabal/bin:$HOME/usr/bin:$HOME/bin:$PATH

    cd "/mnt/store/melpa"

    PKGDIR=$(make get-pkgdir)
    [ -e $PKGDIR/errors.log ] &&
        mv $PKGDIR/errors.log $PKGDIR/errors-previous.log

    make -k -j8 $(find recipes/ -type f | sort) || true
}

build_all
