#!/bin/bash -e

export LANG=en_US.UTF-8

function kill_all_jobs { jobs -p | xargs kill; }
trap kill_all_jobs SIGINT SIGTERM

function build_all {
    PATH=$HOME/.cabal/bin:$HOME/usr/bin:$HOME/bin:$PATH

    cd "/mnt/store/melpa"
    make -k -j8 $(find recipes/ -type f | sort) || true
}

build_all
