#!/bin/bash -e

export LANG=en_US.UTF-8

function unix_timestamp {
    date "+%s"
}

function kill_all_jobs { jobs -p | xargs kill; }
trap kill_all_jobs SIGINT SIGTERM


function build_all {
    PATH=$HOME/.cabal/bin:$HOME/usr/bin:$HOME/bin:$PATH

    ## run the script
    cd "/mnt/store/melpa"
    make -k -j8 $(find recipes/ -type f | sort) || true

    echo '{"completed":' "$(unix_timestamp)" '}' > html/build-status.json
}

build_all
