#!/bin/bash -e

export HOME=/home/melpa
cd ${HOME}/melpa

source $HOME/melpa/scripts/env

## git pull
cd ${MELPA_HOME}
git fetch origin
git reset --hard origin/${MELPA_BRANCH}
git pull origin ${MELPA_BRANCH}
echo

# Build all the packages.
scripts/parallel_build_all

echo '{"completed":' `date "+%s"` '}' > /home/melpa/www/build-status.json

# Sleep for an hour before rebuilding.
sleep 1h
