;;; package --- Summary:
;;; autocorrect.el corrects mispelled American English words as you type them!

;;; Commentary:
;;; The more technical thing, is that autocorrect.el saves these abbreviations
;;; into your global-abbrev-table, and then turns on abbrev-mode
;;; I got the list from here:
;;; https://en.wikipedia.org/wiki/Commonly_misspelled_English_words
;;;
;;; BUT there is a more complete list here:
;;; https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/A
;;;
;;; Libreoffice also has a long list of commenly mispelled words, that could be
;;; added, but I'm not sure how to export their list.

;;; Code:

;;; Begin imported code from Artur Malabara
;;; http://endlessparentheses.com/ispell-and-abbrev-the-perfect-auto-correct.html

(global-set-key (kbd "C-c $") #'endless/ispell-word-then-abbrev)

(defun endless/ispell-word-then-abbrev (p)
  "Call `ispell-word', then create an abbrev for it.
With prefix P, create local abbrev. Otherwise it will
be global."
  (interactive "P")
  (let (bef aft)
    (save-excursion
      (while (progn
               (backward-word)
               (and (setq bef (thing-at-point 'word))
                    (not (ispell-word nil 'quiet)))))
      (setq aft (thing-at-point 'word)))
    (when (and aft bef (not (equal aft bef)))
      (setq aft (downcase aft))
      (setq bef (downcase bef))
      (define-abbrev
        (if p local-abbrev-table global-abbrev-table)
        bef aft)
      (message "\"%s\" now expands to \"%s\" %sally"
               bef aft (if p "loc" "glob")))))

(setq save-abbrevs 'silently)
(setq-default abbrev-mode t)

;;; end imported code

(length correction-list)

(setq correction-list
      '(("Carribean" "Caribbean" nil 0)
        ("absance" "absence" nil 0)
        ("acceptible" "acceptable" nil 0)
        ("accidentaly" "accidentally" nil 0)
        ("acheive" "achieve" nil 0)
        ("adress" "address" nil 0)
        ("adultary" "adultery" nil 0)
        ("agression" "aggression" nil 0)
        ("agressive" "aggressive" nil 0)
        ("allmost" "almost" nil 1)
        ("alot" "a lot" nil 0)
        ("aquit" "acquit" nil 0)
        ("arguement" "argument" nil 0)
        ("artic" "arctic" nil 0)
        ("athiest" "atheist" nil 0)
        ("becomeing" "becoming" nil 0)
        ("becuase" "because" nil 0)
        ("begining" "beginning" nil 0)
        ("beleive" "believe" nil 2)
        ("bellweather" "bellwether" nil 0)
        ("buisness" "business" nil 0)
        ("calender" "calendar" nil 0)
        ("capital" "capitol" nil 0)
        ("catagory" "category" nil 0)
        ("cemetary" "cemetery" nil 0)
        ("changable" "changeable" nil 0)
        ("cheif" "chief" nil 0)
        ("collectable" "collectible" nil 0)
        ("colum" "column" nil 0)
        ("comming" "coming" nil 0)
        ("conceed" "concede" nil 0)
        ("congradulate" "congratulate" nil 0)
        ("consciencious" "conscientious" nil 0)
        ("consensus" "concensus" nil 0)
        ("contraversy" "controversy" nil 0)
        ("cooly" "coolly" nil 0)
        ("decieve" "deceive" nil 0)
        ("definate" "definite" nil 0)
        ("definitely" "definitly" nil 1)
        ("definitly" "definitely" nil 6)
        ("desparate" "desperate" nil 0)
        ("diffrence" "difference" nil 0)
        ("dilema" "dilemma" nil 0)
        ("disapoint" "disappoint" nil 0)
        ("disasterous" "disastrous" nil 0)
        ("drunkeness" "drunkenness" nil 0)
        ("dumbell" "dumbbell" nil 0)
        ("embarass" "embarrass" nil 0)
        ("equipment" "equiptment" nil 0)
        ("excede" "exceed" nil 0)
        ("exilerate" "exhilarate" nil 0)
        ("existance" "existence" nil 0)
        ("experiance" "experience" nil 0)
        ("extreem" "extreme" nil 0)
        ("facinating" "fascinating" nil 0)
        ("firey" "fiery" nil 0)
        ("flourescent" "fluorescent" nil 0)
        ("foriegn" "foreign" nil 0)
        ("freind" "friend" nil 0)
        ("fullfil" "fulfill" nil 0)
        ("guage" "gauge" nil 0)
        ("guidence" "guidance" nil 0)
        ("harrass" "harass" nil 0)
        ("heirarchy" "hierarchy" nil 0)
        ("humerous" "humorous" nil 0)
        ("ignorence" "ignorance" nil 0)
        ("imediately" "immediately" nil 0)
        ("immitate" "imitate" nil 0)
        ("independant" "independent" nil 0)
        ("indispensible" "indispensable" nil 0)
        ("innoculate" "inoculate" nil 0)
        ("jewelery" "jewelry" nil 0)
        ("judgement" "judgment" nil 0)
        ("kernal" "kernel" nil 0)
        ("liason" "liaison" nil 0)
        ("liesure" "leisure" nil 0)
        ("lightening" "lightning" nil 0)
        ("lisence" "license" nil 0)
        ("miniscule" "minuscule" nil 0)
        ("miniture" "miniature" nil 0)
        ("momento" "memento" nil 0)
        ("neice" "niece" nil 0)
        ("nieghbor" "neighbor" nil 0)
        ("noticable" "noticeable" nil 0)
        ("occassion" "occasion" nil 0)
        ("occured" "occurred" nil 0)
        ("orignal" "original" nil 0)
        ("outragous" "outrageous" nil 0)
        ("parliment" "parliament" nil 0)
        ("percieve" "perceive" nil 0)
        ("perseverence" "perseverance" nil 0)
        ("plagerize" "plagiarize" nil 0)
        ("potatos" "potatoes" nil 0)
        ("preceed" "precede" nil 0)
        ("presance" "presence" nil 0)
        ("principal" "principle" nil 0)
        ("professer" "professor" nil 0)
        ("promiss" "promise" nil 0)
        ("pronounciation" "pronunciation" nil 0)
        ("prufe" "proof" nil 0)
        ("publically" "publicly" nil 0)
        ("quarentine" "quarantine" nil 0)
        ("que" "queue" nil 0)
        ("readible" "readable" nil 0)
        ("realy" "really" nil 0)
        ("reciept" "receipt" nil 0)
        ("recieve" "receive" nil 0)
        ("refered" "referred" nil 0)
        ("repitition" "repetition" nil 0)
        ("rtrn" "return" nil 0)
        ("sargent" "sergeant" nil 0)
        ("seperate" "separate" nil 0)
        ("sieze" "seize" nil 0)
        ("similer" "similar" nil 0)
        ("supercede" "supersede" nil 0)
        ("teh" "the" nil 6)
        ("thinsg" "things" nil 1)
        ("tomatos" "tomatoes" nil 0)
        ("tommorrow" "tomorrow" nil 0)
        ("twelth" "twelfth" nil 0)
        ("tyrany" "tyranny" nil 0)
        ("underate" "underrate" nil 0)
        ("undertsand" "understand" nil 1)
        ("untill" "until" nil 0)
        ("upholstry" "upholstery" nil 0)
        ("vehical" "vehicle" nil 0)
        ("visious" "vicious" nil 0)
        ("w/" "with" nil 0)
        ("w/o" "without" nil 0)
        ("wether" "whether" nil 0)
        ("wierd" "weird" nil 0)
        ("wilfull" "wilful" nil 0)
        ("withhold" "withold" nil 0)))
